language: node_js

script:
  - echo "hello world"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./
  github_token: $GITHUB_TOKEN # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
